version: "2.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    volumes:
      - .:/dvna
    depends_on:
      - mysql-db
    env_file:
      - ./vars.env

  mysql-db:
    image: mysql:5.7
    expose:
      - "1433"
    env_file:
      - ./vars.env
